-- Seed the marketplace with the original demo catalog.
-- Run once in the Supabase SQL Editor, after schema.sql.

insert into public.listings (title, price, category, seller, location, condition, description, story)
values
  ('Reclaimed Wood Shelf', 45, array['Furniture', 'Wood'], 'EcoWoodworks', 'Portland, OR', 'Like New', 'A floating shelf built from reclaimed Douglas fir barn wood. Hand-sanded and finished with food-safe oil. 24" x 8".', 'Salvaged from a century-old barn slated for demolition outside Portland — every knot and nail hole is original.'),
  ('Upcycled Denim Tote Bag', 22, array['Fashion', 'Bags'], 'ThreadRevival', 'Austin, TX', 'New (upcycled)', 'Roomy everyday tote sewn from three pairs of reclaimed denim jeans, with a canvas lining and reinforced straps.', 'Made from donated jeans that no longer fit their owners — nothing about them was worn out.'),
  ('Vintage Mason Jar Lamp', 38, array['Lighting', 'Vintage'], 'GlowGreen', 'Brooklyn, NY', 'Good', 'A wide-mouth mason jar wired into a warm-glow table lamp, mounted on a reclaimed wood base. Includes a dimmable bulb.', 'The jar came from a shuttered upstate general store; the base is offcut oak from a furniture shop''s scrap bin.'),
  ('Repurposed Bike Wheel Clock', 60, array['Decor', 'Industrial'], 'CycleArt', 'Denver, CO', 'Good', 'A working wall clock built around a 26" bicycle wheel, spokes intact, with a quiet quartz movement at the hub.', 'The wheel came off a commuter bike that was totaled in a collision — the rider donated it rather than scrap it.'),
  ('Upcycled Pallet Coffee Table', 85, array['Furniture', 'Pallet'], 'PalletWorks', 'Seattle, WA', 'New (upcycled)', 'Low-profile coffee table built from stacked shipping pallet boards on locking caster wheels. Seats a tray or stack of books nicely.', 'Built from pallets pulled from a warehouse loading dock before they were headed to the incinerator.'),
  ('Tin Can Herb Planter Set', 18, array['Garden', 'Planters'], 'GreenThumb', 'Chicago, IL', 'New (upcycled)', 'Set of three drainage-drilled tin cans, hand-painted and ready for a windowsill herb garden.', 'Cans collected from a neighborhood restaurant''s recycling bin, cleaned and given a second life.'),
  ('Sari Silk Patchwork Pillow', 30, array['Textiles', 'Home'], 'SilkRevive', 'San Francisco, CA', 'New (upcycled)', '18" throw pillow cover patchworked from remnant sari silk in warm jewel tones. Cover only, insert not included.', 'Sewn from offcuts left over from a sari tailoring shop that would otherwise have gone to landfill.'),
  ('Upcycled Tire Ottoman', 55, array['Furniture', 'Industrial'], 'TreadDesigns', 'Nashville, TN', 'Good', 'A retired tire, wrapped in braided jute rope and topped with a cushioned wood lid — doubles as extra seating or a side table.', 'Sourced from a local tire shop''s pile of worn treads that couldn''t be resold or retreaded.'),
  ('Bottle Cap Mosaic Mirror', 48, array['Decor', 'Art'], 'CapCraft', 'Miami, FL', 'New (upcycled)', 'Round wall mirror framed in a hand-laid mosaic of flattened bottle caps in ocean blues and greens.', 'Caps collected over a year from local bars and restaurants as part of a neighborhood cleanup initiative.');
